version: '3'

services:
  drupal:
    image: drupal:latest
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_USER=drupal_user
      - DRUPAL_DATABASE_PASSWORD=drupal_password
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal_user
      - MYSQL_PASSWORD=drupal_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  drupal_data:
  db_data:
